// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Data.Database;

#nullable disable

namespace UserService.Data.Migrations
{
    [DbContext(typeof(UserserviceDbContext))]
    ///[Migration("20220607001536_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserService.Domain.Entities.UserMetaInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserMetaInformation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Bio = "I am Jia anu",
                            DisplayName = "Jia Anu",
                            UserName = "jia.anu"
                        },
                        new
                        {
                            Id = 2L,
                            Bio = "I am Naina anu",
                            DisplayName = "Naina Anu",
                            UserName = "naina.anu"
                        },
                        new
                        {
                            Id = 3L,
                            Bio = "I am Sreena anu",
                            DisplayName = "Sreena Anu",
                            UserName = "sreena.anu"
                        },
                        new
                        {
                            Id = 4L,
                            Bio = "I am Admin",
                            DisplayName = "Admin",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
