// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Data.Database;

#nullable disable

namespace UserService.Data.Migrations
{
    [DbContext(typeof(UserserviceDbContext))]
    partial class UserserviceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserService.Data.Interfaces.Entities.UserFollower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FolloweeId")
                        .HasColumnType("bigint");

                    b.Property<long>("FollowerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId");

                    b.ToTable("UserFollower");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FolloweeId = 2L,
                            FollowerId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            FolloweeId = 3L,
                            FollowerId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            FolloweeId = 4L,
                            FollowerId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            FolloweeId = 5L,
                            FollowerId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            FolloweeId = 6L,
                            FollowerId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            FolloweeId = 7L,
                            FollowerId = 5L
                        },
                        new
                        {
                            Id = 7L,
                            FolloweeId = 8L,
                            FollowerId = 6L
                        },
                        new
                        {
                            Id = 8L,
                            FolloweeId = 9L,
                            FollowerId = 7L
                        },
                        new
                        {
                            Id = 9L,
                            FolloweeId = 10L,
                            FollowerId = 8L
                        },
                        new
                        {
                            Id = 10L,
                            FolloweeId = 11L,
                            FollowerId = 9L
                        },
                        new
                        {
                            Id = 11L,
                            FolloweeId = 12L,
                            FollowerId = 10L
                        },
                        new
                        {
                            Id = 12L,
                            FolloweeId = 13L,
                            FollowerId = 11L
                        },
                        new
                        {
                            Id = 13L,
                            FolloweeId = 14L,
                            FollowerId = 12L
                        },
                        new
                        {
                            Id = 14L,
                            FolloweeId = 15L,
                            FollowerId = 13L
                        },
                        new
                        {
                            Id = 15L,
                            FolloweeId = 16L,
                            FollowerId = 14L
                        },
                        new
                        {
                            Id = 16L,
                            FolloweeId = 17L,
                            FollowerId = 15L
                        },
                        new
                        {
                            Id = 17L,
                            FolloweeId = 18L,
                            FollowerId = 16L
                        },
                        new
                        {
                            Id = 18L,
                            FolloweeId = 19L,
                            FollowerId = 17L
                        },
                        new
                        {
                            Id = 19L,
                            FolloweeId = 20L,
                            FollowerId = 18L
                        },
                        new
                        {
                            Id = 20L,
                            FolloweeId = 21L,
                            FollowerId = 19L
                        },
                        new
                        {
                            Id = 21L,
                            FolloweeId = 22L,
                            FollowerId = 20L
                        },
                        new
                        {
                            Id = 22L,
                            FolloweeId = 23L,
                            FollowerId = 21L
                        },
                        new
                        {
                            Id = 23L,
                            FolloweeId = 24L,
                            FollowerId = 22L
                        },
                        new
                        {
                            Id = 24L,
                            FolloweeId = 25L,
                            FollowerId = 23L
                        },
                        new
                        {
                            Id = 25L,
                            FolloweeId = 26L,
                            FollowerId = 24L
                        },
                        new
                        {
                            Id = 26L,
                            FolloweeId = 27L,
                            FollowerId = 25L
                        },
                        new
                        {
                            Id = 27L,
                            FolloweeId = 28L,
                            FollowerId = 26L
                        },
                        new
                        {
                            Id = 28L,
                            FolloweeId = 29L,
                            FollowerId = 27L
                        },
                        new
                        {
                            Id = 29L,
                            FolloweeId = 30L,
                            FollowerId = 28L
                        },
                        new
                        {
                            Id = 30L,
                            FolloweeId = 31L,
                            FollowerId = 29L
                        },
                        new
                        {
                            Id = 31L,
                            FolloweeId = 32L,
                            FollowerId = 30L
                        },
                        new
                        {
                            Id = 32L,
                            FolloweeId = 33L,
                            FollowerId = 31L
                        },
                        new
                        {
                            Id = 33L,
                            FolloweeId = 34L,
                            FollowerId = 32L
                        },
                        new
                        {
                            Id = 34L,
                            FolloweeId = 35L,
                            FollowerId = 33L
                        },
                        new
                        {
                            Id = 35L,
                            FolloweeId = 36L,
                            FollowerId = 34L
                        },
                        new
                        {
                            Id = 36L,
                            FolloweeId = 37L,
                            FollowerId = 35L
                        },
                        new
                        {
                            Id = 37L,
                            FolloweeId = 38L,
                            FollowerId = 36L
                        },
                        new
                        {
                            Id = 38L,
                            FolloweeId = 39L,
                            FollowerId = 37L
                        },
                        new
                        {
                            Id = 39L,
                            FolloweeId = 40L,
                            FollowerId = 38L
                        },
                        new
                        {
                            Id = 40L,
                            FolloweeId = 41L,
                            FollowerId = 39L
                        },
                        new
                        {
                            Id = 41L,
                            FolloweeId = 42L,
                            FollowerId = 40L
                        },
                        new
                        {
                            Id = 42L,
                            FolloweeId = 43L,
                            FollowerId = 41L
                        },
                        new
                        {
                            Id = 43L,
                            FolloweeId = 44L,
                            FollowerId = 42L
                        },
                        new
                        {
                            Id = 44L,
                            FolloweeId = 45L,
                            FollowerId = 43L
                        },
                        new
                        {
                            Id = 45L,
                            FolloweeId = 46L,
                            FollowerId = 44L
                        },
                        new
                        {
                            Id = 46L,
                            FolloweeId = 47L,
                            FollowerId = 45L
                        },
                        new
                        {
                            Id = 47L,
                            FolloweeId = 48L,
                            FollowerId = 46L
                        },
                        new
                        {
                            Id = 48L,
                            FolloweeId = 49L,
                            FollowerId = 47L
                        },
                        new
                        {
                            Id = 49L,
                            FolloweeId = 50L,
                            FollowerId = 48L
                        },
                        new
                        {
                            Id = 50L,
                            FolloweeId = 1L,
                            FollowerId = 49L
                        },
                        new
                        {
                            Id = 51L,
                            FolloweeId = 50L,
                            FollowerId = 1L
                        },
                        new
                        {
                            Id = 52L,
                            FolloweeId = 1L,
                            FollowerId = 2L
                        },
                        new
                        {
                            Id = 53L,
                            FolloweeId = 2L,
                            FollowerId = 3L
                        },
                        new
                        {
                            Id = 54L,
                            FolloweeId = 5L,
                            FollowerId = 4L
                        });
                });

            modelBuilder.Entity("UserService.Data.Interfaces.Entities.UserMetaInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserMetaInformation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Bio = "I am jia anu",
                            DisplayName = "Jia Anu",
                            UserName = "jia.anu"
                        },
                        new
                        {
                            Id = 2L,
                            Bio = "I am naina anu",
                            DisplayName = "Naina Anu",
                            UserName = "naina.anu"
                        },
                        new
                        {
                            Id = 3L,
                            Bio = "I am priya smith",
                            DisplayName = "Priya Smith",
                            UserName = "priya.smith"
                        },
                        new
                        {
                            Id = 4L,
                            Bio = "I am rajan kumar",
                            DisplayName = "Rajan Kumar",
                            UserName = "rajan.kumar"
                        },
                        new
                        {
                            Id = 5L,
                            Bio = "I am surya karthik",
                            DisplayName = "Surya Karthik",
                            UserName = "surya.karthik"
                        },
                        new
                        {
                            Id = 6L,
                            Bio = "I am anjali menon",
                            DisplayName = "Anjali Menon",
                            UserName = "anjali.menon"
                        },
                        new
                        {
                            Id = 7L,
                            Bio = "I am manju pillai",
                            DisplayName = "Manju Pillai",
                            UserName = "manju.pillai"
                        },
                        new
                        {
                            Id = 8L,
                            Bio = "I am reema johnson",
                            DisplayName = "Reema Johnson",
                            UserName = "reema.johnson"
                        },
                        new
                        {
                            Id = 9L,
                            Bio = "I am sona roy",
                            DisplayName = "Sona Roy",
                            UserName = "sona.roy"
                        },
                        new
                        {
                            Id = 10L,
                            Bio = "I am ajay sharma",
                            DisplayName = "Ajay Sharma",
                            UserName = "ajay.sharma"
                        },
                        new
                        {
                            Id = 11L,
                            Bio = "I am mukesh singh",
                            DisplayName = "Mukesh Singh",
                            UserName = "mukesh.singh"
                        },
                        new
                        {
                            Id = 12L,
                            Bio = "I am ranjan verma",
                            DisplayName = "Ranjan Verma",
                            UserName = "ranjan.verma"
                        },
                        new
                        {
                            Id = 13L,
                            Bio = "I am tina kapoor",
                            DisplayName = "Tina Kapoor",
                            UserName = "tina.kapoor"
                        },
                        new
                        {
                            Id = 14L,
                            Bio = "I am jayan murali",
                            DisplayName = "Jayan Murali",
                            UserName = "jayan.murali"
                        },
                        new
                        {
                            Id = 15L,
                            Bio = "I am shiva singh",
                            DisplayName = "Shiva Singh",
                            UserName = "shiva.singh"
                        },
                        new
                        {
                            Id = 16L,
                            Bio = "I am pradeep gupta",
                            DisplayName = "Pradeep Gupta",
                            UserName = "pradeep.gupta"
                        },
                        new
                        {
                            Id = 17L,
                            Bio = "I am seema khan",
                            DisplayName = "Seema Khan",
                            UserName = "seema.khan"
                        },
                        new
                        {
                            Id = 18L,
                            Bio = "I am geetha singh",
                            DisplayName = "Geetha Singh",
                            UserName = "geetha.singh"
                        },
                        new
                        {
                            Id = 19L,
                            Bio = "I am krishna raj",
                            DisplayName = "Krishna Raj",
                            UserName = "krishna.raj"
                        },
                        new
                        {
                            Id = 20L,
                            Bio = "I am babu malhotra",
                            DisplayName = "Babu Malhotra",
                            UserName = "babu.malhotra"
                        },
                        new
                        {
                            Id = 21L,
                            Bio = "I am pavi kumar",
                            DisplayName = "Pavi Kumar",
                            UserName = "pavi.kumar"
                        },
                        new
                        {
                            Id = 22L,
                            Bio = "I am manu jain",
                            DisplayName = "Manu Jain",
                            UserName = "manu.jain"
                        },
                        new
                        {
                            Id = 23L,
                            Bio = "I am rajesh agarwal",
                            DisplayName = "Rajesh Agarwal",
                            UserName = "rajesh.agarwal"
                        },
                        new
                        {
                            Id = 24L,
                            Bio = "I am neha sharma",
                            DisplayName = "Neha Sharma",
                            UserName = "neha.sharma"
                        },
                        new
                        {
                            Id = 25L,
                            Bio = "I am prabha sen",
                            DisplayName = "Prabha Sen",
                            UserName = "prabha.sen"
                        },
                        new
                        {
                            Id = 26L,
                            Bio = "I am krish kapoor",
                            DisplayName = "Krish Kapoor",
                            UserName = "krish.kapoor"
                        },
                        new
                        {
                            Id = 27L,
                            Bio = "I am sasi roy",
                            DisplayName = "Sasi Roy",
                            UserName = "sasi.roy"
                        },
                        new
                        {
                            Id = 28L,
                            Bio = "I am george fernandes",
                            DisplayName = "George Fernandes",
                            UserName = "george.fernandes"
                        },
                        new
                        {
                            Id = 29L,
                            Bio = "I am shalini singh",
                            DisplayName = "Shalini Singh",
                            UserName = "shalini.singh"
                        },
                        new
                        {
                            Id = 30L,
                            Bio = "I am varsha menon",
                            DisplayName = "Varsha Menon",
                            UserName = "varsha.menon"
                        },
                        new
                        {
                            Id = 31L,
                            Bio = "I am lalitha nair",
                            DisplayName = "Lalitha Nair",
                            UserName = "lalitha.nair"
                        },
                        new
                        {
                            Id = 32L,
                            Bio = "I am sunil singh",
                            DisplayName = "Sunil Singh",
                            UserName = "sunil.singh"
                        },
                        new
                        {
                            Id = 33L,
                            Bio = "I am manoj sharma",
                            DisplayName = "Manoj Sharma",
                            UserName = "manoj.sharma"
                        },
                        new
                        {
                            Id = 34L,
                            Bio = "I am radhika bansal",
                            DisplayName = "Radhika Bansal",
                            UserName = "radhika.bansal"
                        },
                        new
                        {
                            Id = 35L,
                            Bio = "I am ravi kapoor",
                            DisplayName = "Ravi Kapoor",
                            UserName = "ravi.kapoor"
                        },
                        new
                        {
                            Id = 36L,
                            Bio = "I am vijay gupta",
                            DisplayName = "Vijay Gupta",
                            UserName = "vijay.gupta"
                        },
                        new
                        {
                            Id = 37L,
                            Bio = "I am meera nair",
                            DisplayName = "Meera Nair",
                            UserName = "meera.nair"
                        },
                        new
                        {
                            Id = 38L,
                            Bio = "I am sundar kumar",
                            DisplayName = "Sundar Kumar",
                            UserName = "sundar.kumar"
                        },
                        new
                        {
                            Id = 39L,
                            Bio = "I am ajith murali",
                            DisplayName = "Ajith Murali",
                            UserName = "ajith.murali"
                        },
                        new
                        {
                            Id = 40L,
                            Bio = "I am chitra singh",
                            DisplayName = "Chitra Singh",
                            UserName = "chitra.singh"
                        },
                        new
                        {
                            Id = 41L,
                            Bio = "I am sunitha khan",
                            DisplayName = "Sunitha Khan",
                            UserName = "sunitha.khan"
                        },
                        new
                        {
                            Id = 42L,
                            Bio = "I am kishore verma",
                            DisplayName = "Kishore Verma",
                            UserName = "kishore.verma"
                        },
                        new
                        {
                            Id = 43L,
                            Bio = "I am rani pillai",
                            DisplayName = "Rani Pillai",
                            UserName = "rani.pillai"
                        },
                        new
                        {
                            Id = 44L,
                            Bio = "I am dinesh patel",
                            DisplayName = "Dinesh Patel",
                            UserName = "dinesh.patel"
                        },
                        new
                        {
                            Id = 45L,
                            Bio = "I am ragini singh",
                            DisplayName = "Ragini Singh",
                            UserName = "ragini.singh"
                        },
                        new
                        {
                            Id = 46L,
                            Bio = "I am kamal rajan",
                            DisplayName = "Kamal Rajan",
                            UserName = "kamal.rajan"
                        },
                        new
                        {
                            Id = 47L,
                            Bio = "I am kamini roy",
                            DisplayName = "Kamini Roy",
                            UserName = "kamini.roy"
                        },
                        new
                        {
                            Id = 48L,
                            Bio = "I am vishal gupta",
                            DisplayName = "Vishal Gupta",
                            UserName = "vishal.gupta"
                        },
                        new
                        {
                            Id = 49L,
                            Bio = "I am anjali agarwal",
                            DisplayName = "Anjali Agarwal",
                            UserName = "anjali.agarwal"
                        },
                        new
                        {
                            Id = 50L,
                            Bio = "I am pravin kumar",
                            DisplayName = "Pravin Kumar",
                            UserName = "pravin.kumar"
                        });
                });

            modelBuilder.Entity("UserService.Data.Interfaces.Entities.UserFollower", b =>
                {
                    b.HasOne("UserService.Data.Interfaces.Entities.UserMetaInformation", "Followee")
                        .WithMany("Following")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("UserService.Data.Interfaces.Entities.UserMetaInformation", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("UserService.Data.Interfaces.Entities.UserMetaInformation", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");
                });
#pragma warning restore 612, 618
        }
    }
}
