# version : '3.4'

services:
  nt.vue:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: .
      dockerfile: Dockerfile
      target: 'develop-stage'
    ports:
      - "8090:80"
    volumes:
      - '.:/app'
