version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    environment:
      MONGO_INITDB_DATABASE: demodb  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123  
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db


  mongodb.express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://root:admin123@host.docker.internal:27017/
    networks:
      common.network:
    depends_on:
      - "mongodb"

  ## Mongo Express to manage MongoDb
  #nt.common.mongoexpress:
  #  image: mongo-express
  #  hostname: nt.common.mongoexpress
  #  container_name: nt.common.mongoexpress
  #  restart: always
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
  #    ME_CONFIG_MONGODB_URL: mongodb://root:admin123@authServiceLog:27017/
  #  networks:
  #    nt.authservice.network:
  #    nt.common.network:    
volumes:
  dbdata:

networks:
  common.network:
    driver: bridge