version: '3.9'

services:
  nt.gateway.service:
    ports:
      # - "8000-8099:80"
      - "8001:80" 
      # - "9001:443"

  nt.orchestrator.service:
    ports:
      # - "8000-8099:80"
      - "8002:80" 

  nt.authservice.service:
    ports:
      - "8101-8105:80"
      # - "9002:443"

  nt.authservice.loadbalancer:
   ports:
     - "8100:80" 

  nt.authservice.db:
    ports:
      - '5432:5432'
  
  nt.userservice.db:
    ports:
        - 1433:1433  


  nt.common.portainer:

    ports:
      - "8080:8000"
      - "9000:9000"

  nt.userservice.service:
    ports:
      - "8301:80"
      # - "9003:443"

  nt.common.rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  #nt.common.mongoexpress:
  #  ports:
  #    - 8081:8081


  # nt.common.grafana:
  #   ports:
  #     - "3000:3000"

  # nt.common.prometheus:
  #   ports:
  #       - '9090:9090'

  nt.common.pgadmin:
    ports:
      - '5050:80'


 