version: '3.9'

services:
  nt.gateway.service:
    ports:
      - "8000-8099:80"
      # - "9001:443"


  nt.authservice.service:
    ports:
      - "8101-8199:80"
      # - "9002:443"

  nt.authservice.loadbalancer:
   ports:
     - "8100:80" 

  nt.authservice.db:
    ports:
      - '5432:5432'
  
  nt.userservice.db:
    ports:
        - 1433:1433  


  nt.common.portainer:

    ports:
      - "8080:8000"
      - "9000:9000"

  nt.userservice.service:
    ports:
      - "8300-8399:80"
      # - "9003:443"

  nt.common.rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672


 