name: DotNetCore-React Workflow

on:
  push:
  pull_request:
    branches: [master]

jobs:
  BuildWebApi:
    name: Build Web Api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-preview.6.20318.15
      - name: Build Web Api
        run: dotnet build --configuration Release
      - name: Execute Unit Tests
        if: ${{ success() }}
        run: dotnet test --no-restore --verbosity normal

  BuildReactApp:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd nt.webclient\reactjs\nt
      - name: Set up Node Js
        uses: actions/setup-node@v1
        with:
          node-version: "v12.18.2"
      - run: npm install
      - run: npm run build --if-present
