name: React Web Client Workflow

on:
  pull_request:
    branches: [master]

jobs:
  # Build React Client
  BuildReactApp:
    name: Build React App
    runs-on: ubuntu-latest
    env:
      working-directory: ./client/nt.webclient/reactjs/nt

    steps:
      - name: Check out Source code
        uses: actions/checkout@v2

      - name: Set up Node Js
        uses: actions/setup-node@v1
        with:
          node-version: "v12.18.2"

      - name: Install npm
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: build solution
        run: npm run build --if-present
        working-directory: ${{env.working-directory}}