name: DotNetCore-React Workflow

on:
  pull_request:
    branches: [master]

jobs:
  # Build Vuejs Client
  BuildVuejsApp:
    name: Build Vuejs App
    runs-on: ubuntu-latest
    env:
      working-directory: ./client/nt.webclient/vuejs/nt

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node Js
        uses: actions/setup-node@v1
        with:
          node-version: "v12.18.2"
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm run build --if-present
        working-directory: ${{env.working-directory}}